services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    expose:
      - "8000"
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: fastapi-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
